<a href="https://colab.research.google.com/github/Ravilodugu12/TNS-practice-session/blob/main/Ravi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#to check the number is prime or not
num = int(input("Enter number"))
count=0
for i in range(1,num+1):
  if(num%i==0):
    count+=1
if(count==2):
  print("its a prime number")
else:
  print("not a prime")


Enter number77
not a prime


In [ ]:
a=44;
print(a)

44


In [ ]:
#program to check even or odd
num = int(input("Enter number"))
if(num%2==0):
  print("Even number")
else :
  print("odd number")

Enter number77
odd number


In [ ]:
#program to check the age
age = 12
if (age>=18):
  print("eligible")
print("program executed successfully")

program executed successfully


In [ ]:
#factorial
digit=5
fact=1
for i in range(1,digit+1):
  fact=fact*i
  print(fact)


1
2
6
24
120


In [ ]:
arr = np.arange(1, 21)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
import numpy as np
arr = np.zeros([2,3])
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import pandas as pd
s=pd.Series([1,2,3,4,5,6,7,8])
print(s)


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64


In [ ]:
import pandas as pd
pandas=pd.Series([1,2,3,4,5])
print(pandas.count)


<bound method Series.count of 0    1
1    2
2    3
3    4
4    5
dtype: int64>


In [37]:
# numpy functions
import numpy as np
arr=([1,2,3,4,5,6,7,8])
print(arr)
arr1=([1,2,3,],[5,6,9])
print(arr1)

arr=np.arange(2,20,2)
print(type(arr))

zero=np.zeros((2,3))
print(zero)

one=np.ones((3,3))
print(one)

a=np.eye(3,3)
print(a)

ar=np.linspace(2,3,4)
print(ar)

arr=((np.random.rand(3,3))*10).astype(int)
print(arr)


[1, 2, 3, 4, 5, 6, 7, 8]
([1, 2, 3], [5, 6, 9])
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2.         2.33333333 2.66666667 3.        ]
[[2 9 1]
 [3 6 0]
 [0 9 1]]


In [30]:
import numpy as np
arr1=([1,2,3,],[4,5,6])
arr2=([2,3,4],[3,4,5])
add=np.sum(arr2)
print(add)

mean=np.mean(arr1)
print(mean)

standard=np.std(arr1)
print(standard)

Min=np.min(arr1)
print(Min)
max=np.max(arr1)
print(max)

argmin=np.argmin(arr1)
print(argmin)
argmax=np.argmax(arr1)
print(argmax)

x=np.array(([3,2],[4,2]))
y=np.array(([1,2],[2,3]))
dot=np.dot(x,y)
print(dot)

mat=np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

unsorted=np.array([3,5,8,9,3,2,4])
print("sorted array:",np.sort(unsorted))

21
3.5
1.707825127659933
1
6
0
5
[[ 7 12]
 [ 8 14]]
[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]
sorted array: [2 3 3 4 5 8 9]
