<a href="https://colab.research.google.com/github/Ravilodugu12/TNS-practice-session/blob/main/Ravi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#to check the number is prime or not
num = int(input("Enter number"))
count=0
for i in range(1,num+1):
  if(num%i==0):
    count+=1
if(count==2):
  print("its a prime number")
else:
  print("not a prime")


Enter number77
not a prime


In [ ]:
a=44;
print(a)

44


In [ ]:
#program to check even or odd
num = int(input("Enter number"))
if(num%2==0):
  print("Even number")
else :
  print("odd number")

Enter number77
odd number


In [ ]:
#program to check the age
age = 12
if (age>=18):
  print("eligible")
print("program executed successfully")

program executed successfully


In [ ]:
#factorial
digit=5
fact=1
for i in range(1,digit+1):
  fact=fact*i
  print(fact)


1
2
6
24
120


In [ ]:
arr = np.arange(1, 21)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
import numpy as np
arr = np.zeros([2,3])
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import pandas as pd
s=pd.Series([1,2,3,4,5,6,7,8])
print(s)


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64


In [ ]:
import pandas as pd
pandas=pd.Series([1,2,3,4,5])
print(pandas.count)


<bound method Series.count of 0    1
1    2
2    3
3    4
4    5
dtype: int64>


In [ ]:
# numpy functions
import numpy as np
arr=([1,2,3,4,5,6,7,8])
print(arr)
arr1=([1,2,3,],[5,6,9])
print(arr1)

arr=np.arange(2,20,2)
print(type(arr))

zero=np.zeros((2,3))
print(zero)

one=np.ones((3,3))
print(one)

a=np.eye(3,3)
print(a)

ar=np.linspace(2,3,4)
print(ar)

arr=((np.random.rand(3,3))*10).astype(int)
print(arr)


[1, 2, 3, 4, 5, 6, 7, 8]
([1, 2, 3], [5, 6, 9])
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2.         2.33333333 2.66666667 3.        ]
[[2 9 1]
 [3 6 0]
 [0 9 1]]


In [ ]:
import numpy as np
arr1=([1,2,3,],[4,5,6])
arr2=([2,3,4],[3,4,5])
add=np.sum(arr2)
print(add)

mean=np.mean(arr1)
print(mean)

standard=np.std(arr1)
print(standard)

Min=np.min(arr1)
print(Min)
max=np.max(arr1)
print(max)

argmin=np.argmin(arr1)
print(argmin)
argmax=np.argmax(arr1)
print(argmax)

x=np.array(([3,2],[4,2]))
y=np.array(([1,2],[2,3]))
dot=np.dot(x,y)
print(dot)

mat=np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

unsorted=np.array([3,5,8,9,3,2,4])
print("sorted array:",np.sort(unsorted))

21
3.5
1.707825127659933
1
6
0
5
[[ 7 12]
 [ 8 14]]
[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]
sorted array: [2 3 3 4 5 8 9]


In [ ]:
import pandas as pd
import numpy as np
data={
    "Product_ID": [100, 101, 102, 103, 104],
    "Product_Name": ["Laptop", "Mobile", "Mouse", "Headphone", "KeyBoard"],
    "Catergory": ["Electronics", "Monitor", "Accessories", "Accessorices", "Furniture"],
    "Price": [1000, 2000, 3000, 4000, 5000],
    "Quantity_Sold": [10, 20, 30, 40, 50]
}

#dataframe
df=pd.DataFrame(data)

#1.load and inspect of dataset
print("Dataset:")
print(df)

#2.handling missing
df.fillna(0,inplace=True)

#3.remove dupliactes
df.drop_duplicates(inplace=True)

#4.create revenue = price * quantity_sold
df["Revenue"]=df["Price"]*df["Quantity_Sold"]
print(df)

#5.products generating revenue above average
avg_revenue=df["Revenue"].mean()
print("\nProducts with Revenue Above Average:")
print(df[df["Revenue"]>avg_revenue])

#6.sort products by revenue
sorted_df=df.sort_values(by="Revenue",ascending=False)
print("\nSorted Dataset:")
print(sorted_df)

#7.category-wise total revenue
category_revenue=df.groupby("Catergory")["Revenue"].sum()
print("\nCategory wise Revenue:")
print(category_revenue)

#8.Numpy statistics on revenue
revenues=np.array(df["Revenue"])
print("\nRevenue Statistics:")
print("Mean Revenue:", np.mean(revenues))
print("Median Revenue:", np.median(revenues))
print("Maximum Revenue:", np.max(revenues))
print("Min Revenue:", np.min(revenues))
print("Standard Deviation:", np.std(revenues))

#9.Best_selling_product
best_selling_product=df[df["Quantity_Sold"]==df["Quantity_Sold"].max()]
print("\nBest Selling Product:")
print(best_selling_product)

#10Sales summary report
print("\nSALES SUMMARY REPORT:")
print("Total Revenue:", df["Revenue"].sum())
print("Total Quantity Sold:", df["Quantity_Sold"].sum())
print("Average Revenue Per Sale:", avg_revenue)


Dataset:
   Product_ID Product_Name     Catergory  Price  Quantity_Sold
0         100       Laptop   Electronics   1000             10
1         101       Mobile       Monitor   2000             20
2         102        Mouse   Accessories   3000             30
3         103    Headphone  Accessorices   4000             40
4         104     KeyBoard     Furniture   5000             50
   Product_ID Product_Name     Catergory  Price  Quantity_Sold  Revenue
0         100       Laptop   Electronics   1000             10    10000
1         101       Mobile       Monitor   2000             20    40000
2         102        Mouse   Accessories   3000             30    90000
3         103    Headphone  Accessorices   4000             40   160000
4         104     KeyBoard     Furniture   5000             50   250000

Products with Revenue Above Average:
   Product_ID Product_Name     Catergory  Price  Quantity_Sold  Revenue
3         103    Headphone  Accessorices   4000             40   160000

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Product_ID": [100, 101, 102, 103, 104],
    "Product_Name": ["Laptop", "Mobile", "Mouse", "Headphone", "Keyboard"],
    "Category": ["Electronics", "Monitor", "Accessories", "Accessories", "Furniture"],
    "Price": [1000, 2000, 3000, 4000, 5000],
    "Quantity_Sold": [10, 20, 30, 40, 50]
}

df = pd.DataFrame(data).fillna(0).drop_duplicates()

df["Revenue"] = df["Price"] * df["Quantity_Sold"]

print("Dataset:\n", df)

avg = df["Revenue"].mean()

print("\nAbove Average Revenue:\n", df[df["Revenue"] > avg])

print("\nSorted by Revenue:\n", df.sort_values("Revenue", ascending=False))

print("\nCategory Revenue:\n", df.groupby("Category")["Revenue"].sum())

print("\nStatistics:")
print("Mean:", np.mean(df["Revenue"]))
print("Median:", np.median(df["Revenue"]))
print("Max:", np.max(df["Revenue"]))
print("Min:", np.min(df["Revenue"]))
print("Std:", np.std(df["Revenue"]))

print("\nBest Selling Product:\n",
      df[df["Quantity_Sold"] == df["Quantity_Sold"].max()])

print("\nTotal Revenue:", df["Revenue"].sum())
print("Total Quantity Sold:", df["Quantity_Sold"].sum())
print("Average Revenue:", avg)

Dataset:
    Product_ID Product_Name     Category  Price  Quantity_Sold  Revenue
0         100       Laptop  Electronics   1000             10    10000
1         101       Mobile      Monitor   2000             20    40000
2         102        Mouse  Accessories   3000             30    90000
3         103    Headphone  Accessories   4000             40   160000
4         104     Keyboard    Furniture   5000             50   250000

Above Average Revenue:
    Product_ID Product_Name     Category  Price  Quantity_Sold  Revenue
3         103    Headphone  Accessories   4000             40   160000
4         104     Keyboard    Furniture   5000             50   250000

Sorted by Revenue:
    Product_ID Product_Name     Category  Price  Quantity_Sold  Revenue
4         104     Keyboard    Furniture   5000             50   250000
3         103    Headphone  Accessories   4000             40   160000
2         102        Mouse  Accessories   3000             30    90000
1         101       M